version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/corniehealth-backend
    overwrite: true
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 900
      runas: root
